[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{{projectNameSnake}}"
version = "0.1.0"
description = "{{projectName}} FastAPI application"
requires-python = ">=3.11"

